---
- name: startpsql
  kubernetes.core.k8s:
    definition:
      kind: StatefulSet
      apiVersion: apps/v1
      metadata:
        name: '{{ ansible_operator_meta.name }}-psql'
        namespace: '{{ ansible_operator_meta.namespace }}'
      spec:
        replicas: "{{ size }}"
        selector:
          matchLabels:
            app: psql
        template:
          metadata:
            labels:
              app: psql
          spec:
            containers:
            - name: psql
              env:
              - name: POSTGRES_PASSWORD
                value: "admin"
              - name: POSTGRES_USER
                value: "user"
              - name: POSTGRES_DB
                value: "db"
              - name: PGDATA
                value: /mnt/pgdata 
              volumeMounts:
                - name: www
                  mountPath: /mnt
              image: "postgres:latest"
              ports:
                - containerPort: 5432
        volumeClaimTemplates:
        - metadata:
            name: www
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 1Gi