apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: psql-pod
  namespace: default
spec:
  serviceName: "psql"
  selector:
    matchLabels:
      app: psql
  replicas: {size}
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
        - name: psql
          image: "{img}"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: admin
          - name: POSTGRES_USER 
            value: user
          - name: POSTGRES_DB
            value: db
          - name: PGDATA
            value: /mnt/pgdata 
          volumeMounts:
            - name: www
              mountPath: /mnt
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi