apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition 
metadata:
  name: psqls.test.com
spec: 
  scope: Namespaced
  group: test.com
  versions: 
    - name: v1 
      served: true 
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: integer
                  minimum: 1
  names: 
    kind: psql 
    plural: psqls 
    singular: psql