apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
  - name: shell-operator
    image: docker.io/$DOCKER_USER/shelloperator
    imagePullPolicy: Always
  serviceAccountName: monitor-pods-acc
